### ISSUE TITLE
I do not see the icons for Apple or Home...

### ISSUE THREAD

**Issue by itlinux** [Falkor/dotfiles#11]
What else does it need (Mac) I follow the steps.I cannot see the icon for the Apple logo or the Home as my home dir.

**Comment by Falkor** [comment]
Have you installed the fonts mentioned on https://github.com/Falkor/dotfiles/tree/master/oh-my-zsh ? Then in iTerm2, under `Preferences / Profiles / <name> / Text`:

* Select `Source Code Pro for Powerline` as Font (Regular / 14pts)
* Select `Hack Nerd Font` as Non-ASCII Font (with checkbox: use a diffferent font for non-ASCII text)


 
If you use iTerm, you need to install the appropriate fonts --

**Comment by Falkor** [comment]
I'll that issue now, reopen it if it does solve your issue.
