### ISSUE TITLE
Error: Invalid Brewfile: undefined method `mac' for #<Bundle::Dsl:0x00007ff824a8d490>

### ISSUE THREAD

**Issue by KarlDSchubertUoA** [Falkor/dotfiles#12]
Hello! I was following the direction in the ReadMe and got to the point of:

     brew bundle --file=/tmp/Brewfile -v

And got this error code:

     Error: Invalid Brewfile: undefined method `mac' for #<Bundle::Dsl:0x00007ff824a8d490>

Everything else beforehand looked like it ran successfully:

brew tap Homebrew/bundle
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
crispy-doom         go@1.15             projectm            rdkit
==> Updated Formulae
Updated 497 formulae.
==> Deleted Formulae
avian                                    geant4
==> New Casks
cog                        nault                      wannianli
font-smoothing-adjuster    redream                    zecwallet-lite
kyokan-bob                 rhino                      zulufx
megax                      the-archive
==> Updated Casks
Updated 173 casks.
==> Deleted Casks
kode54-cog                               protonmail-unofficial
mega                                     rhinoceros

==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5839 (delta 0), reused 0 (delta 0), pack-reused 5835
Receiving objects: 100% (5839/5839), 1.33 MiB | 8.72 MiB/s, done.
Resolving deltas: 100% (3423/3423), done.
Tapped 1 command (109 files, 1.7MB).
➜  ~ curl -o /tmp/Brewfile https://raw.githubusercontent.com/Falkor/dotfiles/master/brew/Brewfile.minimal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1014  100  1014    0     0   5393      0 --:--:-- --:--:-- --:--:--  5393

I am on a Mac:

![image](https://user-images.githubusercontent.com/45079388/109532799-1bc0fd80-7a7f-11eb-973d-6825843ea8ed.png)

I am doing this in preparation to installing Powerlevel10k following the directions here:

     https://medium.com/weekly-webtips/my-terminal-setu-iterm2-zsh-powerlevel10k-f7101ffc72c2

Thank you for your help!  

Sincerely,

Karl.

**Comment by Falkor** [comment]
the `mac` entry comes from the brew 'mas'. 

Can you try to install it manually beforehand ? 

```
brew install mas
```

**Comment by Falkor** [comment]
Oups, my bad, it was indeed a mistake -- should be prefixed by `mas`.

**Comment by KarlDSchubertUoA** [comment]
That worked fine.  When I then issued the "brew tap Homebrew/bundle":
  
brew tap homebrew/bundle                                                                                                                     06:58:38
brew bundle --file=/tmp/Brewfile -v
Error: No Brewfile found
