### ISSUE TITLE
CHanging Theme to dark

### ISSUE THREAD

**Issue by cmartinio** [Falkor/dotfiles#16]
Hi there, other than the documentation is there another way for me to study your dotfiles? I really like the way it is structured but I can't seem to wrap my head around it. Some help regarding modifying vim theme would very helpful. I tried changing the theme from light to dark but it still remained light. if you could can you please email me the explanation at fxgx99@gmail.com? Thanks in advance

**Comment by Falkor** [comment]
No sorry, not by mail, make a proper issue ;) I edit it to put your question in description.  
Changing the following line: 
https://github.com/Falkor/dotfiles/blob/master/vim/config/theme.vim#L10
as follows: 

```diff
--- config/theme.vim.orig	2022-04-27 10:46:51.000000000 +0200
+++ config/theme.vim	2022-04-27 10:47:00.000000000 +0200
@@ -7,7 +7,7 @@

 " Actual Color Scheme {{{
 " ---------
-set background=light     " use 'dark' or 'light'
+set background=dark     " use 'dark' or 'light'
 colorscheme PaperColor
 " highlight BadWhitespace ctermfg=darkred ctermbg=black guifg=#382424 guibg=black
```
should do the job.
