### ISSUE TITLE
How can I delete rvm status when unecessary?

### ISSUE THREAD

**Issue by eailfly** [Falkor/dotfiles#6]
Hi, I see your screenshot, it seems that since you run 'rvm use 2.1' then it shows rvm status on the right prompt, befor that it don't have that. How can you do that? I use rvm and powerlevel9k too, but I have rvm status on my right prompt all the time, how can I delete it when unnecessary?

**Comment by Falkor** [comment]
Hi @eailfly 

if you use your system ruby (`rvm use system`) then nothing is display in the rvm plugin - it is configured like that. I personally set it as default behavior (_i.e._ to use the system ruby be default) which explains why noting is displayed at the beginning.

**Comment by eailfly** [comment]
tried this and it worked!!! thangk you.
