### ISSUE TITLE
how to show git icon and battery ?on zsh

### ISSUE THREAD

**Issue by mardianto** [Falkor/dotfiles#8]

**Comment by Falkor** [comment]
It comes from the [powerlevel9k](https://github.com/bhilburn/powerlevel9k) theme used with the appropriate font -- see [`docs/oh-my-zsh/README.md`](http://falkor-dotfiles.readthedocs.io/en/latest/oh-my-zsh/README/):

~~~bash
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs virtualenv rbenv rvm time)
~~~

I personally customized it in my [`falkor.plugin.zsh`](https://github.com/Falkor/dotfiles/blob/master/oh-my-zsh/custom/plugins/falkor/falkor.plugin.zsh) yet you can just place the customization of the [powerlevel9k prompt segment](https://github.com/bhilburn/powerlevel9k#customizing-prompt-segments) wherever you want.
