### ISSUE TITLE
Dead Font

### ISSUE THREAD

**Issue by MatchSG** [Falkor/dotfiles#9]
Font links are all dead

**Comment by Falkor** [comment]
Thanks for noticing it, indeed the [github repo](https://github.com/stefano-meschiari/dotemacs)  I was referring to no longer exists. 
As I couldn't find the font back easily, I decided to export and publish the one I'm using -- you will find it [here](https://github.com/Falkor/dotfiles/blob/master/fonts/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf) _i.e._ under the [`fonts/`](https://github.com/Falkor/dotfiles/tree/master/fonts/) directory.

I updated the [oh-my-zsh/README.md](https://github.com/Falkor/dotfiles/blob/master/oh-my-zsh/README.md) file and added a link to my blog post for details on the configuration of iTerm2 people might be interested to follow -- see [this link](https://varrette.gforge.uni.lu/blog/2017/01/17/configuring-mac-os-on-your-brand-new-laptop/#iterm2-configuration).
